security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # Aquí le decimos que cargue los usuarios buscando por el campo 'email'
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # <--- IMPORTANTE: En el antiguo era username, aquí es email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            # --- ESTILO ANTIGUO (Nativo de Symfony) ---
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                # Le decimos que el campo del formulario se llama '_username' (aunque metan el email)
                username_parameter: _username
                password_parameter: _password
                # Redirección al éxito (Portada)
                default_target_path: app_home
            # ------------------------------------------

            logout:
                path: app_logout
                # A donde ir al salir
                target: app_home

    # Control de acceso
    access_control:
        # Rutas públicas
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        # Solo administradores pueden entrar a rutas que empiecen por /admin
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Usuarios logueados
        # - { path: ^/pokemon, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon